export const dummyFollowing = [
   {
      login: 'ry',
      id: 80,
      node_id: 'MDQ6VXNlcjgw',
      avatar_url: 'https://avatars.githubusercontent.com/u/80?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ry',
      html_url: 'https://github.com/ry',
      followers_url: 'https://api.github.com/users/ry/followers',
      following_url: 'https://api.github.com/users/ry/following{/other_user}',
      gists_url: 'https://api.github.com/users/ry/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ry/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ry/subscriptions',
      organizations_url: 'https://api.github.com/users/ry/orgs',
      repos_url: 'https://api.github.com/users/ry/repos',
      events_url: 'https://api.github.com/users/ry/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ry/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'mikeal',
      id: 579,
      node_id: 'MDQ6VXNlcjU3OQ==',
      avatar_url: 'https://avatars.githubusercontent.com/u/579?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/mikeal',
      html_url: 'https://github.com/mikeal',
      followers_url: 'https://api.github.com/users/mikeal/followers',
      following_url: 'https://api.github.com/users/mikeal/following{/other_user}',
      gists_url: 'https://api.github.com/users/mikeal/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/mikeal/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/mikeal/subscriptions',
      organizations_url: 'https://api.github.com/users/mikeal/orgs',
      repos_url: 'https://api.github.com/users/mikeal/repos',
      events_url: 'https://api.github.com/users/mikeal/events{/privacy}',
      received_events_url: 'https://api.github.com/users/mikeal/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'mitchellh',
      id: 1299,
      node_id: 'MDQ6VXNlcjEyOTk=',
      avatar_url: 'https://avatars.githubusercontent.com/u/1299?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/mitchellh',
      html_url: 'https://github.com/mitchellh',
      followers_url: 'https://api.github.com/users/mitchellh/followers',
      following_url: 'https://api.github.com/users/mitchellh/following{/other_user}',
      gists_url: 'https://api.github.com/users/mitchellh/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/mitchellh/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/mitchellh/subscriptions',
      organizations_url: 'https://api.github.com/users/mitchellh/orgs',
      repos_url: 'https://api.github.com/users/mitchellh/repos',
      events_url: 'https://api.github.com/users/mitchellh/events{/privacy}',
      received_events_url: 'https://api.github.com/users/mitchellh/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'akitaonrails',
      id: 2840,
      node_id: 'MDQ6VXNlcjI4NDA=',
      avatar_url: 'https://avatars.githubusercontent.com/u/2840?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/akitaonrails',
      html_url: 'https://github.com/akitaonrails',
      followers_url: 'https://api.github.com/users/akitaonrails/followers',
      following_url: 'https://api.github.com/users/akitaonrails/following{/other_user}',
      gists_url: 'https://api.github.com/users/akitaonrails/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/akitaonrails/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/akitaonrails/subscriptions',
      organizations_url: 'https://api.github.com/users/akitaonrails/orgs',
      repos_url: 'https://api.github.com/users/akitaonrails/repos',
      events_url: 'https://api.github.com/users/akitaonrails/events{/privacy}',
      received_events_url: 'https://api.github.com/users/akitaonrails/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'tonyarnold',
      id: 4802,
      node_id: 'MDQ6VXNlcjQ4MDI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/4802?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/tonyarnold',
      html_url: 'https://github.com/tonyarnold',
      followers_url: 'https://api.github.com/users/tonyarnold/followers',
      following_url: 'https://api.github.com/users/tonyarnold/following{/other_user}',
      gists_url: 'https://api.github.com/users/tonyarnold/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/tonyarnold/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/tonyarnold/subscriptions',
      organizations_url: 'https://api.github.com/users/tonyarnold/orgs',
      repos_url: 'https://api.github.com/users/tonyarnold/repos',
      events_url: 'https://api.github.com/users/tonyarnold/events{/privacy}',
      received_events_url: 'https://api.github.com/users/tonyarnold/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'sophiebits',
      id: 6820,
      node_id: 'MDQ6VXNlcjY4MjA=',
      avatar_url: 'https://avatars.githubusercontent.com/u/6820?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/sophiebits',
      html_url: 'https://github.com/sophiebits',
      followers_url: 'https://api.github.com/users/sophiebits/followers',
      following_url: 'https://api.github.com/users/sophiebits/following{/other_user}',
      gists_url: 'https://api.github.com/users/sophiebits/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/sophiebits/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/sophiebits/subscriptions',
      organizations_url: 'https://api.github.com/users/sophiebits/orgs',
      repos_url: 'https://api.github.com/users/sophiebits/repos',
      events_url: 'https://api.github.com/users/sophiebits/events{/privacy}',
      received_events_url: 'https://api.github.com/users/sophiebits/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'mattt',
      id: 7659,
      node_id: 'MDQ6VXNlcjc2NTk=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7659?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/mattt',
      html_url: 'https://github.com/mattt',
      followers_url: 'https://api.github.com/users/mattt/followers',
      following_url: 'https://api.github.com/users/mattt/following{/other_user}',
      gists_url: 'https://api.github.com/users/mattt/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/mattt/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/mattt/subscriptions',
      organizations_url: 'https://api.github.com/users/mattt/orgs',
      repos_url: 'https://api.github.com/users/mattt/repos',
      events_url: 'https://api.github.com/users/mattt/events{/privacy}',
      received_events_url: 'https://api.github.com/users/mattt/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'nuxlli',
      id: 8738,
      node_id: 'MDQ6VXNlcjg3Mzg=',
      avatar_url: 'https://avatars.githubusercontent.com/u/8738?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/nuxlli',
      html_url: 'https://github.com/nuxlli',
      followers_url: 'https://api.github.com/users/nuxlli/followers',
      following_url: 'https://api.github.com/users/nuxlli/following{/other_user}',
      gists_url: 'https://api.github.com/users/nuxlli/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/nuxlli/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/nuxlli/subscriptions',
      organizations_url: 'https://api.github.com/users/nuxlli/orgs',
      repos_url: 'https://api.github.com/users/nuxlli/repos',
      events_url: 'https://api.github.com/users/nuxlli/events{/privacy}',
      received_events_url: 'https://api.github.com/users/nuxlli/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'isaacs',
      id: 9287,
      node_id: 'MDQ6VXNlcjkyODc=',
      avatar_url: 'https://avatars.githubusercontent.com/u/9287?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/isaacs',
      html_url: 'https://github.com/isaacs',
      followers_url: 'https://api.github.com/users/isaacs/followers',
      following_url: 'https://api.github.com/users/isaacs/following{/other_user}',
      gists_url: 'https://api.github.com/users/isaacs/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/isaacs/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/isaacs/subscriptions',
      organizations_url: 'https://api.github.com/users/isaacs/orgs',
      repos_url: 'https://api.github.com/users/isaacs/repos',
      events_url: 'https://api.github.com/users/isaacs/events{/privacy}',
      received_events_url: 'https://api.github.com/users/isaacs/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'josevalim',
      id: 9582,
      node_id: 'MDQ6VXNlcjk1ODI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/9582?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/josevalim',
      html_url: 'https://github.com/josevalim',
      followers_url: 'https://api.github.com/users/josevalim/followers',
      following_url: 'https://api.github.com/users/josevalim/following{/other_user}',
      gists_url: 'https://api.github.com/users/josevalim/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/josevalim/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/josevalim/subscriptions',
      organizations_url: 'https://api.github.com/users/josevalim/orgs',
      repos_url: 'https://api.github.com/users/josevalim/repos',
      events_url: 'https://api.github.com/users/josevalim/events{/privacy}',
      received_events_url: 'https://api.github.com/users/josevalim/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'henriquebastos',
      id: 12066,
      node_id: 'MDQ6VXNlcjEyMDY2',
      avatar_url: 'https://avatars.githubusercontent.com/u/12066?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/henriquebastos',
      html_url: 'https://github.com/henriquebastos',
      followers_url: 'https://api.github.com/users/henriquebastos/followers',
      following_url: 'https://api.github.com/users/henriquebastos/following{/other_user}',
      gists_url: 'https://api.github.com/users/henriquebastos/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/henriquebastos/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/henriquebastos/subscriptions',
      organizations_url: 'https://api.github.com/users/henriquebastos/orgs',
      repos_url: 'https://api.github.com/users/henriquebastos/repos',
      events_url: 'https://api.github.com/users/henriquebastos/events{/privacy}',
      received_events_url: 'https://api.github.com/users/henriquebastos/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'rauchg',
      id: 13041,
      node_id: 'MDQ6VXNlcjEzMDQx',
      avatar_url: 'https://avatars.githubusercontent.com/u/13041?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/rauchg',
      html_url: 'https://github.com/rauchg',
      followers_url: 'https://api.github.com/users/rauchg/followers',
      following_url: 'https://api.github.com/users/rauchg/following{/other_user}',
      gists_url: 'https://api.github.com/users/rauchg/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/rauchg/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/rauchg/subscriptions',
      organizations_url: 'https://api.github.com/users/rauchg/orgs',
      repos_url: 'https://api.github.com/users/rauchg/repos',
      events_url: 'https://api.github.com/users/rauchg/events{/privacy}',
      received_events_url: 'https://api.github.com/users/rauchg/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'zkat',
      id: 17535,
      node_id: 'MDQ6VXNlcjE3NTM1',
      avatar_url: 'https://avatars.githubusercontent.com/u/17535?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/zkat',
      html_url: 'https://github.com/zkat',
      followers_url: 'https://api.github.com/users/zkat/followers',
      following_url: 'https://api.github.com/users/zkat/following{/other_user}',
      gists_url: 'https://api.github.com/users/zkat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/zkat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/zkat/subscriptions',
      organizations_url: 'https://api.github.com/users/zkat/orgs',
      repos_url: 'https://api.github.com/users/zkat/repos',
      events_url: 'https://api.github.com/users/zkat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/zkat/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'mpj',
      id: 17815,
      node_id: 'MDQ6VXNlcjE3ODE1',
      avatar_url: 'https://avatars.githubusercontent.com/u/17815?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/mpj',
      html_url: 'https://github.com/mpj',
      followers_url: 'https://api.github.com/users/mpj/followers',
      following_url: 'https://api.github.com/users/mpj/following{/other_user}',
      gists_url: 'https://api.github.com/users/mpj/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/mpj/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/mpj/subscriptions',
      organizations_url: 'https://api.github.com/users/mpj/orgs',
      repos_url: 'https://api.github.com/users/mpj/repos',
      events_url: 'https://api.github.com/users/mpj/events{/privacy}',
      received_events_url: 'https://api.github.com/users/mpj/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'stevegraham',
      id: 18622,
      node_id: 'MDQ6VXNlcjE4NjIy',
      avatar_url: 'https://avatars.githubusercontent.com/u/18622?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/stevegraham',
      html_url: 'https://github.com/stevegraham',
      followers_url: 'https://api.github.com/users/stevegraham/followers',
      following_url: 'https://api.github.com/users/stevegraham/following{/other_user}',
      gists_url: 'https://api.github.com/users/stevegraham/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/stevegraham/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/stevegraham/subscriptions',
      organizations_url: 'https://api.github.com/users/stevegraham/orgs',
      repos_url: 'https://api.github.com/users/stevegraham/repos',
      events_url: 'https://api.github.com/users/stevegraham/events{/privacy}',
      received_events_url: 'https://api.github.com/users/stevegraham/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'sebastianbergmann',
      id: 25218,
      node_id: 'MDQ6VXNlcjI1MjE4',
      avatar_url: 'https://avatars.githubusercontent.com/u/25218?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/sebastianbergmann',
      html_url: 'https://github.com/sebastianbergmann',
      followers_url: 'https://api.github.com/users/sebastianbergmann/followers',
      following_url: 'https://api.github.com/users/sebastianbergmann/following{/other_user}',
      gists_url: 'https://api.github.com/users/sebastianbergmann/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/sebastianbergmann/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/sebastianbergmann/subscriptions',
      organizations_url: 'https://api.github.com/users/sebastianbergmann/orgs',
      repos_url: 'https://api.github.com/users/sebastianbergmann/repos',
      events_url: 'https://api.github.com/users/sebastianbergmann/events{/privacy}',
      received_events_url: 'https://api.github.com/users/sebastianbergmann/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'tj',
      id: 25254,
      node_id: 'MDQ6VXNlcjI1MjU0',
      avatar_url: 'https://avatars.githubusercontent.com/u/25254?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/tj',
      html_url: 'https://github.com/tj',
      followers_url: 'https://api.github.com/users/tj/followers',
      following_url: 'https://api.github.com/users/tj/following{/other_user}',
      gists_url: 'https://api.github.com/users/tj/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/tj/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/tj/subscriptions',
      organizations_url: 'https://api.github.com/users/tj/orgs',
      repos_url: 'https://api.github.com/users/tj/repos',
      events_url: 'https://api.github.com/users/tj/events{/privacy}',
      received_events_url: 'https://api.github.com/users/tj/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'wilkerlucio',
      id: 25736,
      node_id: 'MDQ6VXNlcjI1NzM2',
      avatar_url: 'https://avatars.githubusercontent.com/u/25736?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/wilkerlucio',
      html_url: 'https://github.com/wilkerlucio',
      followers_url: 'https://api.github.com/users/wilkerlucio/followers',
      following_url: 'https://api.github.com/users/wilkerlucio/following{/other_user}',
      gists_url: 'https://api.github.com/users/wilkerlucio/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/wilkerlucio/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/wilkerlucio/subscriptions',
      organizations_url: 'https://api.github.com/users/wilkerlucio/orgs',
      repos_url: 'https://api.github.com/users/wilkerlucio/repos',
      events_url: 'https://api.github.com/users/wilkerlucio/events{/privacy}',
      received_events_url: 'https://api.github.com/users/wilkerlucio/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'kreigne',
      id: 26656,
      node_id: 'MDQ6VXNlcjI2NjU2',
      avatar_url: 'https://avatars.githubusercontent.com/u/26656?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/kreigne',
      html_url: 'https://github.com/kreigne',
      followers_url: 'https://api.github.com/users/kreigne/followers',
      following_url: 'https://api.github.com/users/kreigne/following{/other_user}',
      gists_url: 'https://api.github.com/users/kreigne/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/kreigne/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/kreigne/subscriptions',
      organizations_url: 'https://api.github.com/users/kreigne/orgs',
      repos_url: 'https://api.github.com/users/kreigne/repos',
      events_url: 'https://api.github.com/users/kreigne/events{/privacy}',
      received_events_url: 'https://api.github.com/users/kreigne/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'skeeto',
      id: 29988,
      node_id: 'MDQ6VXNlcjI5OTg4',
      avatar_url: 'https://avatars.githubusercontent.com/u/29988?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/skeeto',
      html_url: 'https://github.com/skeeto',
      followers_url: 'https://api.github.com/users/skeeto/followers',
      following_url: 'https://api.github.com/users/skeeto/following{/other_user}',
      gists_url: 'https://api.github.com/users/skeeto/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/skeeto/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/skeeto/subscriptions',
      organizations_url: 'https://api.github.com/users/skeeto/orgs',
      repos_url: 'https://api.github.com/users/skeeto/repos',
      events_url: 'https://api.github.com/users/skeeto/events{/privacy}',
      received_events_url: 'https://api.github.com/users/skeeto/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'gilbarbara',
      id: 31954,
      node_id: 'MDQ6VXNlcjMxOTU0',
      avatar_url: 'https://avatars.githubusercontent.com/u/31954?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gilbarbara',
      html_url: 'https://github.com/gilbarbara',
      followers_url: 'https://api.github.com/users/gilbarbara/followers',
      following_url: 'https://api.github.com/users/gilbarbara/following{/other_user}',
      gists_url: 'https://api.github.com/users/gilbarbara/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/gilbarbara/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/gilbarbara/subscriptions',
      organizations_url: 'https://api.github.com/users/gilbarbara/orgs',
      repos_url: 'https://api.github.com/users/gilbarbara/repos',
      events_url: 'https://api.github.com/users/gilbarbara/events{/privacy}',
      received_events_url: 'https://api.github.com/users/gilbarbara/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'avelino',
      id: 31996,
      node_id: 'MDQ6VXNlcjMxOTk2',
      avatar_url: 'https://avatars.githubusercontent.com/u/31996?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/avelino',
      html_url: 'https://github.com/avelino',
      followers_url: 'https://api.github.com/users/avelino/followers',
      following_url: 'https://api.github.com/users/avelino/following{/other_user}',
      gists_url: 'https://api.github.com/users/avelino/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/avelino/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/avelino/subscriptions',
      organizations_url: 'https://api.github.com/users/avelino/orgs',
      repos_url: 'https://api.github.com/users/avelino/repos',
      events_url: 'https://api.github.com/users/avelino/events{/privacy}',
      received_events_url: 'https://api.github.com/users/avelino/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'tve',
      id: 39480,
      node_id: 'MDQ6VXNlcjM5NDgw',
      avatar_url: 'https://avatars.githubusercontent.com/u/39480?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/tve',
      html_url: 'https://github.com/tve',
      followers_url: 'https://api.github.com/users/tve/followers',
      following_url: 'https://api.github.com/users/tve/following{/other_user}',
      gists_url: 'https://api.github.com/users/tve/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/tve/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/tve/subscriptions',
      organizations_url: 'https://api.github.com/users/tve/orgs',
      repos_url: 'https://api.github.com/users/tve/repos',
      events_url: 'https://api.github.com/users/tve/events{/privacy}',
      received_events_url: 'https://api.github.com/users/tve/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'ninetails',
      id: 40065,
      node_id: 'MDQ6VXNlcjQwMDY1',
      avatar_url: 'https://avatars.githubusercontent.com/u/40065?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ninetails',
      html_url: 'https://github.com/ninetails',
      followers_url: 'https://api.github.com/users/ninetails/followers',
      following_url: 'https://api.github.com/users/ninetails/following{/other_user}',
      gists_url: 'https://api.github.com/users/ninetails/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ninetails/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ninetails/subscriptions',
      organizations_url: 'https://api.github.com/users/ninetails/orgs',
      repos_url: 'https://api.github.com/users/ninetails/repos',
      events_url: 'https://api.github.com/users/ninetails/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ninetails/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'leebyron',
      id: 50130,
      node_id: 'MDQ6VXNlcjUwMTMw',
      avatar_url: 'https://avatars.githubusercontent.com/u/50130?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/leebyron',
      html_url: 'https://github.com/leebyron',
      followers_url: 'https://api.github.com/users/leebyron/followers',
      following_url: 'https://api.github.com/users/leebyron/following{/other_user}',
      gists_url: 'https://api.github.com/users/leebyron/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/leebyron/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/leebyron/subscriptions',
      organizations_url: 'https://api.github.com/users/leebyron/orgs',
      repos_url: 'https://api.github.com/users/leebyron/repos',
      events_url: 'https://api.github.com/users/leebyron/events{/privacy}',
      received_events_url: 'https://api.github.com/users/leebyron/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'knolleary',
      id: 51083,
      node_id: 'MDQ6VXNlcjUxMDgz',
      avatar_url: 'https://avatars.githubusercontent.com/u/51083?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/knolleary',
      html_url: 'https://github.com/knolleary',
      followers_url: 'https://api.github.com/users/knolleary/followers',
      following_url: 'https://api.github.com/users/knolleary/following{/other_user}',
      gists_url: 'https://api.github.com/users/knolleary/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/knolleary/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/knolleary/subscriptions',
      organizations_url: 'https://api.github.com/users/knolleary/orgs',
      repos_url: 'https://api.github.com/users/knolleary/repos',
      events_url: 'https://api.github.com/users/knolleary/events{/privacy}',
      received_events_url: 'https://api.github.com/users/knolleary/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'Corelio',
      id: 52606,
      node_id: 'MDQ6VXNlcjUyNjA2',
      avatar_url: 'https://avatars.githubusercontent.com/u/52606?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Corelio',
      html_url: 'https://github.com/Corelio',
      followers_url: 'https://api.github.com/users/Corelio/followers',
      following_url: 'https://api.github.com/users/Corelio/following{/other_user}',
      gists_url: 'https://api.github.com/users/Corelio/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Corelio/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Corelio/subscriptions',
      organizations_url: 'https://api.github.com/users/Corelio/orgs',
      repos_url: 'https://api.github.com/users/Corelio/repos',
      events_url: 'https://api.github.com/users/Corelio/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Corelio/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'diogok',
      id: 53630,
      node_id: 'MDQ6VXNlcjUzNjMw',
      avatar_url: 'https://avatars.githubusercontent.com/u/53630?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/diogok',
      html_url: 'https://github.com/diogok',
      followers_url: 'https://api.github.com/users/diogok/followers',
      following_url: 'https://api.github.com/users/diogok/following{/other_user}',
      gists_url: 'https://api.github.com/users/diogok/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/diogok/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/diogok/subscriptions',
      organizations_url: 'https://api.github.com/users/diogok/orgs',
      repos_url: 'https://api.github.com/users/diogok/repos',
      events_url: 'https://api.github.com/users/diogok/events{/privacy}',
      received_events_url: 'https://api.github.com/users/diogok/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'gitster',
      id: 54884,
      node_id: 'MDQ6VXNlcjU0ODg0',
      avatar_url: 'https://avatars.githubusercontent.com/u/54884?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gitster',
      html_url: 'https://github.com/gitster',
      followers_url: 'https://api.github.com/users/gitster/followers',
      following_url: 'https://api.github.com/users/gitster/following{/other_user}',
      gists_url: 'https://api.github.com/users/gitster/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/gitster/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/gitster/subscriptions',
      organizations_url: 'https://api.github.com/users/gitster/orgs',
      repos_url: 'https://api.github.com/users/gitster/repos',
      events_url: 'https://api.github.com/users/gitster/events{/privacy}',
      received_events_url: 'https://api.github.com/users/gitster/received_events',
      type: 'User',
      site_admin: false,
   },
   {
      login: 'trestini',
      id: 56967,
      node_id: 'MDQ6VXNlcjU2OTY3',
      avatar_url: 'https://avatars.githubusercontent.com/u/56967?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/trestini',
      html_url: 'https://github.com/trestini',
      followers_url: 'https://api.github.com/users/trestini/followers',
      following_url: 'https://api.github.com/users/trestini/following{/other_user}',
      gists_url: 'https://api.github.com/users/trestini/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/trestini/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/trestini/subscriptions',
      organizations_url: 'https://api.github.com/users/trestini/orgs',
      repos_url: 'https://api.github.com/users/trestini/repos',
      events_url: 'https://api.github.com/users/trestini/events{/privacy}',
      received_events_url: 'https://api.github.com/users/trestini/received_events',
      type: 'User',
      site_admin: false,
   },
];

export const dummyRepos = [
   {
      id: 4662742,
      node_id: 'MDEwOlJlcG9zaXRvcnk0NjYyNzQy',
      name: 'bime-api',
      full_name: 'nicolas/bime-api',
      private: false,
      owner: {
         login: 'nicolas',
         id: 6000,
         node_id: 'MDQ6VXNlcjYwMDA=',
         avatar_url: 'https://avatars.githubusercontent.com/u/6000?v=4',
         gravatar_id: '',
         url: 'https://api.github.com/users/nicolas',
         html_url: 'https://github.com/nicolas',
         followers_url: 'https://api.github.com/users/nicolas/followers',
         following_url: 'https://api.github.com/users/nicolas/following{/other_user}',
         gists_url: 'https://api.github.com/users/nicolas/gists{/gist_id}',
         starred_url: 'https://api.github.com/users/nicolas/starred{/owner}{/repo}',
         subscriptions_url: 'https://api.github.com/users/nicolas/subscriptions',
         organizations_url: 'https://api.github.com/users/nicolas/orgs',
         repos_url: 'https://api.github.com/users/nicolas/repos',
         events_url: 'https://api.github.com/users/nicolas/events{/privacy}',
         received_events_url: 'https://api.github.com/users/nicolas/received_events',
         type: 'User',
         site_admin: false,
      },
      html_url: 'https://github.com/nicolas/bime-api',
      description: 'The official documentation of the Bime API',
      fork: false,
      url: 'https://api.github.com/repos/nicolas/bime-api',
      forks_url: 'https://api.github.com/repos/nicolas/bime-api/forks',
      keys_url: 'https://api.github.com/repos/nicolas/bime-api/keys{/key_id}',
      collaborators_url:
         'https://api.github.com/repos/nicolas/bime-api/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/nicolas/bime-api/teams',
      hooks_url: 'https://api.github.com/repos/nicolas/bime-api/hooks',
      issue_events_url: 'https://api.github.com/repos/nicolas/bime-api/issues/events{/number}',
      events_url: 'https://api.github.com/repos/nicolas/bime-api/events',
      assignees_url: 'https://api.github.com/repos/nicolas/bime-api/assignees{/user}',
      branches_url: 'https://api.github.com/repos/nicolas/bime-api/branches{/branch}',
      tags_url: 'https://api.github.com/repos/nicolas/bime-api/tags',
      blobs_url: 'https://api.github.com/repos/nicolas/bime-api/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/nicolas/bime-api/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/nicolas/bime-api/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/nicolas/bime-api/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/nicolas/bime-api/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/nicolas/bime-api/languages',
      stargazers_url: 'https://api.github.com/repos/nicolas/bime-api/stargazers',
      contributors_url: 'https://api.github.com/repos/nicolas/bime-api/contributors',
      subscribers_url: 'https://api.github.com/repos/nicolas/bime-api/subscribers',
      subscription_url: 'https://api.github.com/repos/nicolas/bime-api/subscription',
      commits_url: 'https://api.github.com/repos/nicolas/bime-api/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/nicolas/bime-api/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/nicolas/bime-api/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/nicolas/bime-api/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/nicolas/bime-api/contents/{+path}',
      compare_url: 'https://api.github.com/repos/nicolas/bime-api/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/nicolas/bime-api/merges',
      archive_url: 'https://api.github.com/repos/nicolas/bime-api/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/nicolas/bime-api/downloads',
      issues_url: 'https://api.github.com/repos/nicolas/bime-api/issues{/number}',
      pulls_url: 'https://api.github.com/repos/nicolas/bime-api/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/nicolas/bime-api/milestones{/number}',
      notifications_url:
         'https://api.github.com/repos/nicolas/bime-api/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/nicolas/bime-api/labels{/name}',
      releases_url: 'https://api.github.com/repos/nicolas/bime-api/releases{/id}',
      deployments_url: 'https://api.github.com/repos/nicolas/bime-api/deployments',
      created_at: '2012-06-14T12:03:47Z',
      updated_at: '2015-08-25T16:15:18Z',
      pushed_at: '2013-11-12T08:23:19Z',
      git_url: 'git://github.com/nicolas/bime-api.git',
      ssh_url: 'git@github.com:nicolas/bime-api.git',
      clone_url: 'https://github.com/nicolas/bime-api.git',
      svn_url: 'https://github.com/nicolas/bime-api',
      homepage: 'http://bimeanalytics.com',
      size: 196,
      stargazers_count: 2,
      watchers_count: 2,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 2,
      default_branch: 'master',
   },
   {
      id: 5123848,
      node_id: 'MDEwOlJlcG9zaXRvcnk1MTIzODQ4',
      name: 'bime-api-demo',
      full_name: 'nicolas/bime-api-demo',
      private: false,
      owner: {
         login: 'nicolas',
         id: 6000,
         node_id: 'MDQ6VXNlcjYwMDA=',
         avatar_url: 'https://avatars.githubusercontent.com/u/6000?v=4',
         gravatar_id: '',
         url: 'https://api.github.com/users/nicolas',
         html_url: 'https://github.com/nicolas',
         followers_url: 'https://api.github.com/users/nicolas/followers',
         following_url: 'https://api.github.com/users/nicolas/following{/other_user}',
         gists_url: 'https://api.github.com/users/nicolas/gists{/gist_id}',
         starred_url: 'https://api.github.com/users/nicolas/starred{/owner}{/repo}',
         subscriptions_url: 'https://api.github.com/users/nicolas/subscriptions',
         organizations_url: 'https://api.github.com/users/nicolas/orgs',
         repos_url: 'https://api.github.com/users/nicolas/repos',
         events_url: 'https://api.github.com/users/nicolas/events{/privacy}',
         received_events_url: 'https://api.github.com/users/nicolas/received_events',
         type: 'User',
         site_admin: false,
      },
      html_url: 'https://github.com/nicolas/bime-api-demo',
      description: 'A rails app that demo the integration with the Bime API',
      fork: false,
      url: 'https://api.github.com/repos/nicolas/bime-api-demo',
      forks_url: 'https://api.github.com/repos/nicolas/bime-api-demo/forks',
      keys_url: 'https://api.github.com/repos/nicolas/bime-api-demo/keys{/key_id}',
      collaborators_url:
         'https://api.github.com/repos/nicolas/bime-api-demo/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/nicolas/bime-api-demo/teams',
      hooks_url: 'https://api.github.com/repos/nicolas/bime-api-demo/hooks',
      issue_events_url: 'https://api.github.com/repos/nicolas/bime-api-demo/issues/events{/number}',
      events_url: 'https://api.github.com/repos/nicolas/bime-api-demo/events',
      assignees_url: 'https://api.github.com/repos/nicolas/bime-api-demo/assignees{/user}',
      branches_url: 'https://api.github.com/repos/nicolas/bime-api-demo/branches{/branch}',
      tags_url: 'https://api.github.com/repos/nicolas/bime-api-demo/tags',
      blobs_url: 'https://api.github.com/repos/nicolas/bime-api-demo/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/nicolas/bime-api-demo/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/nicolas/bime-api-demo/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/nicolas/bime-api-demo/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/nicolas/bime-api-demo/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/nicolas/bime-api-demo/languages',
      stargazers_url: 'https://api.github.com/repos/nicolas/bime-api-demo/stargazers',
      contributors_url: 'https://api.github.com/repos/nicolas/bime-api-demo/contributors',
      subscribers_url: 'https://api.github.com/repos/nicolas/bime-api-demo/subscribers',
      subscription_url: 'https://api.github.com/repos/nicolas/bime-api-demo/subscription',
      commits_url: 'https://api.github.com/repos/nicolas/bime-api-demo/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/nicolas/bime-api-demo/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/nicolas/bime-api-demo/comments{/number}',
      issue_comment_url:
         'https://api.github.com/repos/nicolas/bime-api-demo/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/nicolas/bime-api-demo/contents/{+path}',
      compare_url: 'https://api.github.com/repos/nicolas/bime-api-demo/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/nicolas/bime-api-demo/merges',
      archive_url: 'https://api.github.com/repos/nicolas/bime-api-demo/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/nicolas/bime-api-demo/downloads',
      issues_url: 'https://api.github.com/repos/nicolas/bime-api-demo/issues{/number}',
      pulls_url: 'https://api.github.com/repos/nicolas/bime-api-demo/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/nicolas/bime-api-demo/milestones{/number}',
      notifications_url:
         'https://api.github.com/repos/nicolas/bime-api-demo/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/nicolas/bime-api-demo/labels{/name}',
      releases_url: 'https://api.github.com/repos/nicolas/bime-api-demo/releases{/id}',
      deployments_url: 'https://api.github.com/repos/nicolas/bime-api-demo/deployments',
      created_at: '2012-07-20T14:06:17Z',
      updated_at: '2014-10-27T11:11:02Z',
      pushed_at: '2022-07-21T22:28:21Z',
      git_url: 'git://github.com/nicolas/bime-api-demo.git',
      ssh_url: 'git@github.com:nicolas/bime-api-demo.git',
      clone_url: 'https://github.com/nicolas/bime-api-demo.git',
      svn_url: 'https://github.com/nicolas/bime-api-demo',
      homepage: null,
      size: 117,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Ruby',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 6,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 6,
      watchers: 0,
      default_branch: 'master',
   },
   {
      id: 10689397,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMDY4OTM5Nw==',
      name: 'bime-api-demo-java',
      full_name: 'nicolas/bime-api-demo-java',
      private: false,
      owner: {
         login: 'nicolas',
         id: 6000,
         node_id: 'MDQ6VXNlcjYwMDA=',
         avatar_url: 'https://avatars.githubusercontent.com/u/6000?v=4',
         gravatar_id: '',
         url: 'https://api.github.com/users/nicolas',
         html_url: 'https://github.com/nicolas',
         followers_url: 'https://api.github.com/users/nicolas/followers',
         following_url: 'https://api.github.com/users/nicolas/following{/other_user}',
         gists_url: 'https://api.github.com/users/nicolas/gists{/gist_id}',
         starred_url: 'https://api.github.com/users/nicolas/starred{/owner}{/repo}',
         subscriptions_url: 'https://api.github.com/users/nicolas/subscriptions',
         organizations_url: 'https://api.github.com/users/nicolas/orgs',
         repos_url: 'https://api.github.com/users/nicolas/repos',
         events_url: 'https://api.github.com/users/nicolas/events{/privacy}',
         received_events_url: 'https://api.github.com/users/nicolas/received_events',
         type: 'User',
         site_admin: false,
      },
      html_url: 'https://github.com/nicolas/bime-api-demo-java',
      description: 'Sample application in JAVA (using the playframework)',
      fork: false,
      url: 'https://api.github.com/repos/nicolas/bime-api-demo-java',
      forks_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/forks',
      keys_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/keys{/key_id}',
      collaborators_url:
         'https://api.github.com/repos/nicolas/bime-api-demo-java/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/teams',
      hooks_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/hooks',
      issue_events_url:
         'https://api.github.com/repos/nicolas/bime-api-demo-java/issues/events{/number}',
      events_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/events',
      assignees_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/assignees{/user}',
      branches_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/branches{/branch}',
      tags_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/tags',
      blobs_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/languages',
      stargazers_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/stargazers',
      contributors_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/contributors',
      subscribers_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/subscribers',
      subscription_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/subscription',
      commits_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/comments{/number}',
      issue_comment_url:
         'https://api.github.com/repos/nicolas/bime-api-demo-java/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/contents/{+path}',
      compare_url:
         'https://api.github.com/repos/nicolas/bime-api-demo-java/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/merges',
      archive_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/downloads',
      issues_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/issues{/number}',
      pulls_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/milestones{/number}',
      notifications_url:
         'https://api.github.com/repos/nicolas/bime-api-demo-java/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/labels{/name}',
      releases_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/releases{/id}',
      deployments_url: 'https://api.github.com/repos/nicolas/bime-api-demo-java/deployments',
      created_at: '2013-06-14T13:24:17Z',
      updated_at: '2016-03-18T15:21:07Z',
      pushed_at: '2013-07-24T14:26:13Z',
      git_url: 'git://github.com/nicolas/bime-api-demo-java.git',
      ssh_url: 'git@github.com:nicolas/bime-api-demo-java.git',
      clone_url: 'https://github.com/nicolas/bime-api-demo-java.git',
      svn_url: 'https://github.com/nicolas/bime-api-demo-java',
      homepage: null,
      size: 488,
      stargazers_count: 1,
      watchers_count: 1,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 1,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 1,
      watchers: 1,
      default_branch: 'master',
   },
   {
      id: 192476984,
      node_id: 'MDEwOlJlcG9zaXRvcnkxOTI0NzY5ODQ=',
      name: 'fastai-v3',
      full_name: 'nicolas/fastai-v3',
      private: false,
      owner: {
         login: 'nicolas',
         id: 6000,
         node_id: 'MDQ6VXNlcjYwMDA=',
         avatar_url: 'https://avatars.githubusercontent.com/u/6000?v=4',
         gravatar_id: '',
         url: 'https://api.github.com/users/nicolas',
         html_url: 'https://github.com/nicolas',
         followers_url: 'https://api.github.com/users/nicolas/followers',
         following_url: 'https://api.github.com/users/nicolas/following{/other_user}',
         gists_url: 'https://api.github.com/users/nicolas/gists{/gist_id}',
         starred_url: 'https://api.github.com/users/nicolas/starred{/owner}{/repo}',
         subscriptions_url: 'https://api.github.com/users/nicolas/subscriptions',
         organizations_url: 'https://api.github.com/users/nicolas/orgs',
         repos_url: 'https://api.github.com/users/nicolas/repos',
         events_url: 'https://api.github.com/users/nicolas/events{/privacy}',
         received_events_url: 'https://api.github.com/users/nicolas/received_events',
         type: 'User',
         site_admin: false,
      },
      html_url: 'https://github.com/nicolas/fastai-v3',
      description: 'Starter app for fastai v3 model deployment on Render',
      fork: true,
      url: 'https://api.github.com/repos/nicolas/fastai-v3',
      forks_url: 'https://api.github.com/repos/nicolas/fastai-v3/forks',
      keys_url: 'https://api.github.com/repos/nicolas/fastai-v3/keys{/key_id}',
      collaborators_url:
         'https://api.github.com/repos/nicolas/fastai-v3/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/nicolas/fastai-v3/teams',
      hooks_url: 'https://api.github.com/repos/nicolas/fastai-v3/hooks',
      issue_events_url: 'https://api.github.com/repos/nicolas/fastai-v3/issues/events{/number}',
      events_url: 'https://api.github.com/repos/nicolas/fastai-v3/events',
      assignees_url: 'https://api.github.com/repos/nicolas/fastai-v3/assignees{/user}',
      branches_url: 'https://api.github.com/repos/nicolas/fastai-v3/branches{/branch}',
      tags_url: 'https://api.github.com/repos/nicolas/fastai-v3/tags',
      blobs_url: 'https://api.github.com/repos/nicolas/fastai-v3/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/nicolas/fastai-v3/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/nicolas/fastai-v3/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/nicolas/fastai-v3/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/nicolas/fastai-v3/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/nicolas/fastai-v3/languages',
      stargazers_url: 'https://api.github.com/repos/nicolas/fastai-v3/stargazers',
      contributors_url: 'https://api.github.com/repos/nicolas/fastai-v3/contributors',
      subscribers_url: 'https://api.github.com/repos/nicolas/fastai-v3/subscribers',
      subscription_url: 'https://api.github.com/repos/nicolas/fastai-v3/subscription',
      commits_url: 'https://api.github.com/repos/nicolas/fastai-v3/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/nicolas/fastai-v3/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/nicolas/fastai-v3/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/nicolas/fastai-v3/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/nicolas/fastai-v3/contents/{+path}',
      compare_url: 'https://api.github.com/repos/nicolas/fastai-v3/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/nicolas/fastai-v3/merges',
      archive_url: 'https://api.github.com/repos/nicolas/fastai-v3/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/nicolas/fastai-v3/downloads',
      issues_url: 'https://api.github.com/repos/nicolas/fastai-v3/issues{/number}',
      pulls_url: 'https://api.github.com/repos/nicolas/fastai-v3/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/nicolas/fastai-v3/milestones{/number}',
      notifications_url:
         'https://api.github.com/repos/nicolas/fastai-v3/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/nicolas/fastai-v3/labels{/name}',
      releases_url: 'https://api.github.com/repos/nicolas/fastai-v3/releases{/id}',
      deployments_url: 'https://api.github.com/repos/nicolas/fastai-v3/deployments',
      created_at: '2019-06-18T06:12:56Z',
      updated_at: '2019-06-18T06:36:55Z',
      pushed_at: '2019-06-18T06:36:53Z',
      git_url: 'git://github.com/nicolas/fastai-v3.git',
      ssh_url: 'git@github.com:nicolas/fastai-v3.git',
      clone_url: 'https://github.com/nicolas/fastai-v3.git',
      svn_url: 'https://github.com/nicolas/fastai-v3',
      homepage: 'https://render.com',
      size: 44,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Python',
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
   },
   {
      id: 587245512,
      node_id: 'R_kgDOIwCnyA',
      name: 'fastai_walkthru',
      full_name: 'nicolas/fastai_walkthru',
      private: false,
      owner: {
         login: 'nicolas',
         id: 6000,
         node_id: 'MDQ6VXNlcjYwMDA=',
         avatar_url: 'https://avatars.githubusercontent.com/u/6000?v=4',
         gravatar_id: '',
         url: 'https://api.github.com/users/nicolas',
         html_url: 'https://github.com/nicolas',
         followers_url: 'https://api.github.com/users/nicolas/followers',
         following_url: 'https://api.github.com/users/nicolas/following{/other_user}',
         gists_url: 'https://api.github.com/users/nicolas/gists{/gist_id}',
         starred_url: 'https://api.github.com/users/nicolas/starred{/owner}{/repo}',
         subscriptions_url: 'https://api.github.com/users/nicolas/subscriptions',
         organizations_url: 'https://api.github.com/users/nicolas/orgs',
         repos_url: 'https://api.github.com/users/nicolas/repos',
         events_url: 'https://api.github.com/users/nicolas/events{/privacy}',
         received_events_url: 'https://api.github.com/users/nicolas/received_events',
         type: 'User',
         site_admin: false,
      },
      html_url: 'https://github.com/nicolas/fastai_walkthru',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/nicolas/fastai_walkthru',
      forks_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/forks',
      keys_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/keys{/key_id}',
      collaborators_url:
         'https://api.github.com/repos/nicolas/fastai_walkthru/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/teams',
      hooks_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/hooks',
      issue_events_url:
         'https://api.github.com/repos/nicolas/fastai_walkthru/issues/events{/number}',
      events_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/events',
      assignees_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/assignees{/user}',
      branches_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/branches{/branch}',
      tags_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/tags',
      blobs_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/languages',
      stargazers_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/stargazers',
      contributors_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/contributors',
      subscribers_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/subscribers',
      subscription_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/subscription',
      commits_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/comments{/number}',
      issue_comment_url:
         'https://api.github.com/repos/nicolas/fastai_walkthru/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/contents/{+path}',
      compare_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/merges',
      archive_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/downloads',
      issues_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/issues{/number}',
      pulls_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/milestones{/number}',
      notifications_url:
         'https://api.github.com/repos/nicolas/fastai_walkthru/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/labels{/name}',
      releases_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/releases{/id}',
      deployments_url: 'https://api.github.com/repos/nicolas/fastai_walkthru/deployments',
      created_at: '2023-01-10T09:54:50Z',
      updated_at: '2023-01-10T10:45:07Z',
      pushed_at: '2023-01-10T10:45:02Z',
      git_url: 'git://github.com/nicolas/fastai_walkthru.git',
      ssh_url: 'git@github.com:nicolas/fastai_walkthru.git',
      clone_url: 'https://github.com/nicolas/fastai_walkthru.git',
      svn_url: 'https://github.com/nicolas/fastai_walkthru',
      homepage: null,
      size: 7,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Jupyter Notebook',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
         key: 'apache-2.0',
         name: 'Apache License 2.0',
         spdx_id: 'Apache-2.0',
         url: 'https://api.github.com/licenses/apache-2.0',
         node_id: 'MDc6TGljZW5zZTI=',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
   },
   {
      id: 587264325,
      node_id: 'R_kgDOIwDxRQ',
      name: 'fastbook',
      full_name: 'nicolas/fastbook',
      private: false,
      owner: {
         login: 'nicolas',
         id: 6000,
         node_id: 'MDQ6VXNlcjYwMDA=',
         avatar_url: 'https://avatars.githubusercontent.com/u/6000?v=4',
         gravatar_id: '',
         url: 'https://api.github.com/users/nicolas',
         html_url: 'https://github.com/nicolas',
         followers_url: 'https://api.github.com/users/nicolas/followers',
         following_url: 'https://api.github.com/users/nicolas/following{/other_user}',
         gists_url: 'https://api.github.com/users/nicolas/gists{/gist_id}',
         starred_url: 'https://api.github.com/users/nicolas/starred{/owner}{/repo}',
         subscriptions_url: 'https://api.github.com/users/nicolas/subscriptions',
         organizations_url: 'https://api.github.com/users/nicolas/orgs',
         repos_url: 'https://api.github.com/users/nicolas/repos',
         events_url: 'https://api.github.com/users/nicolas/events{/privacy}',
         received_events_url: 'https://api.github.com/users/nicolas/received_events',
         type: 'User',
         site_admin: false,
      },
      html_url: 'https://github.com/nicolas/fastbook',
      description: 'The fastai book, published as Jupyter Notebooks',
      fork: true,
      url: 'https://api.github.com/repos/nicolas/fastbook',
      forks_url: 'https://api.github.com/repos/nicolas/fastbook/forks',
      keys_url: 'https://api.github.com/repos/nicolas/fastbook/keys{/key_id}',
      collaborators_url:
         'https://api.github.com/repos/nicolas/fastbook/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/nicolas/fastbook/teams',
      hooks_url: 'https://api.github.com/repos/nicolas/fastbook/hooks',
      issue_events_url: 'https://api.github.com/repos/nicolas/fastbook/issues/events{/number}',
      events_url: 'https://api.github.com/repos/nicolas/fastbook/events',
      assignees_url: 'https://api.github.com/repos/nicolas/fastbook/assignees{/user}',
      branches_url: 'https://api.github.com/repos/nicolas/fastbook/branches{/branch}',
      tags_url: 'https://api.github.com/repos/nicolas/fastbook/tags',
      blobs_url: 'https://api.github.com/repos/nicolas/fastbook/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/nicolas/fastbook/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/nicolas/fastbook/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/nicolas/fastbook/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/nicolas/fastbook/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/nicolas/fastbook/languages',
      stargazers_url: 'https://api.github.com/repos/nicolas/fastbook/stargazers',
      contributors_url: 'https://api.github.com/repos/nicolas/fastbook/contributors',
      subscribers_url: 'https://api.github.com/repos/nicolas/fastbook/subscribers',
      subscription_url: 'https://api.github.com/repos/nicolas/fastbook/subscription',
      commits_url: 'https://api.github.com/repos/nicolas/fastbook/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/nicolas/fastbook/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/nicolas/fastbook/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/nicolas/fastbook/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/nicolas/fastbook/contents/{+path}',
      compare_url: 'https://api.github.com/repos/nicolas/fastbook/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/nicolas/fastbook/merges',
      archive_url: 'https://api.github.com/repos/nicolas/fastbook/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/nicolas/fastbook/downloads',
      issues_url: 'https://api.github.com/repos/nicolas/fastbook/issues{/number}',
      pulls_url: 'https://api.github.com/repos/nicolas/fastbook/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/nicolas/fastbook/milestones{/number}',
      notifications_url:
         'https://api.github.com/repos/nicolas/fastbook/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/nicolas/fastbook/labels{/name}',
      releases_url: 'https://api.github.com/repos/nicolas/fastbook/releases{/id}',
      deployments_url: 'https://api.github.com/repos/nicolas/fastbook/deployments',
      created_at: '2023-01-10T10:50:40Z',
      updated_at: '2023-01-10T11:05:07Z',
      pushed_at: '2023-01-10T11:04:51Z',
      git_url: 'git://github.com/nicolas/fastbook.git',
      ssh_url: 'git@github.com:nicolas/fastbook.git',
      clone_url: 'https://github.com/nicolas/fastbook.git',
      svn_url: 'https://github.com/nicolas/fastbook',
      homepage: '',
      size: 80240,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Jupyter Notebook',
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
         key: 'other',
         name: 'Other',
         spdx_id: 'NOASSERTION',
         url: null,
         node_id: 'MDc6TGljZW5zZTA=',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
   },
   {
      id: 50575729,
      node_id: 'MDEwOlJlcG9zaXRvcnk1MDU3NTcyOQ==',
      name: 'Front-end-Developer-Interview-Questions',
      full_name: 'nicolas/Front-end-Developer-Interview-Questions',
      private: false,
      owner: {
         login: 'nicolas',
         id: 6000,
         node_id: 'MDQ6VXNlcjYwMDA=',
         avatar_url: 'https://avatars.githubusercontent.com/u/6000?v=4',
         gravatar_id: '',
         url: 'https://api.github.com/users/nicolas',
         html_url: 'https://github.com/nicolas',
         followers_url: 'https://api.github.com/users/nicolas/followers',
         following_url: 'https://api.github.com/users/nicolas/following{/other_user}',
         gists_url: 'https://api.github.com/users/nicolas/gists{/gist_id}',
         starred_url: 'https://api.github.com/users/nicolas/starred{/owner}{/repo}',
         subscriptions_url: 'https://api.github.com/users/nicolas/subscriptions',
         organizations_url: 'https://api.github.com/users/nicolas/orgs',
         repos_url: 'https://api.github.com/users/nicolas/repos',
         events_url: 'https://api.github.com/users/nicolas/events{/privacy}',
         received_events_url: 'https://api.github.com/users/nicolas/received_events',
         type: 'User',
         site_admin: false,
      },
      html_url: 'https://github.com/nicolas/Front-end-Developer-Interview-Questions',
      description:
         'A list of helpful front-end related questions you can use to interview potential candidates, test yourself or completely ignore.',
      fork: true,
      url: 'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions',
      forks_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/forks',
      keys_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/keys{/key_id}',
      collaborators_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/collaborators{/collaborator}',
      teams_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/teams',
      hooks_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/hooks',
      issue_events_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/issues/events{/number}',
      events_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/events',
      assignees_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/assignees{/user}',
      branches_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/branches{/branch}',
      tags_url: 'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/tags',
      blobs_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/git/blobs{/sha}',
      git_tags_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/git/tags{/sha}',
      git_refs_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/git/refs{/sha}',
      trees_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/git/trees{/sha}',
      statuses_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/statuses/{sha}',
      languages_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/languages',
      stargazers_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/stargazers',
      contributors_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/contributors',
      subscribers_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/subscribers',
      subscription_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/subscription',
      commits_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/commits{/sha}',
      git_commits_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/git/commits{/sha}',
      comments_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/comments{/number}',
      issue_comment_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/issues/comments{/number}',
      contents_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/contents/{+path}',
      compare_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/compare/{base}...{head}',
      merges_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/merges',
      archive_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/{archive_format}{/ref}',
      downloads_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/downloads',
      issues_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/issues{/number}',
      pulls_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/pulls{/number}',
      milestones_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/milestones{/number}',
      notifications_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/notifications{?since,all,participating}',
      labels_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/labels{/name}',
      releases_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/releases{/id}',
      deployments_url:
         'https://api.github.com/repos/nicolas/Front-end-Developer-Interview-Questions/deployments',
      created_at: '2016-01-28T10:35:53Z',
      updated_at: '2016-01-28T10:34:51Z',
      pushed_at: '2016-01-10T03:43:42Z',
      git_url: 'git://github.com/nicolas/Front-end-Developer-Interview-Questions.git',
      ssh_url: 'git@github.com:nicolas/Front-end-Developer-Interview-Questions.git',
      clone_url: 'https://github.com/nicolas/Front-end-Developer-Interview-Questions.git',
      svn_url: 'https://github.com/nicolas/Front-end-Developer-Interview-Questions',
      homepage: 'http://h5bp.github.io/Front-end-Developer-Interview-Questions/',
      size: 1001,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
         key: 'mit',
         name: 'MIT License',
         spdx_id: 'MIT',
         url: 'https://api.github.com/licenses/mit',
         node_id: 'MDc6TGljZW5zZTEz',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
   },
   {
      id: 199440762,
      node_id: 'MDEwOlJlcG9zaXRvcnkxOTk0NDA3NjI=',
      name: 'mangafacedetector',
      full_name: 'nicolas/mangafacedetector',
      private: false,
      owner: {
         login: 'nicolas',
         id: 6000,
         node_id: 'MDQ6VXNlcjYwMDA=',
         avatar_url: 'https://avatars.githubusercontent.com/u/6000?v=4',
         gravatar_id: '',
         url: 'https://api.github.com/users/nicolas',
         html_url: 'https://github.com/nicolas',
         followers_url: 'https://api.github.com/users/nicolas/followers',
         following_url: 'https://api.github.com/users/nicolas/following{/other_user}',
         gists_url: 'https://api.github.com/users/nicolas/gists{/gist_id}',
         starred_url: 'https://api.github.com/users/nicolas/starred{/owner}{/repo}',
         subscriptions_url: 'https://api.github.com/users/nicolas/subscriptions',
         organizations_url: 'https://api.github.com/users/nicolas/orgs',
         repos_url: 'https://api.github.com/users/nicolas/repos',
         events_url: 'https://api.github.com/users/nicolas/events{/privacy}',
         received_events_url: 'https://api.github.com/users/nicolas/received_events',
         type: 'User',
         site_admin: false,
      },
      html_url: 'https://github.com/nicolas/mangafacedetector',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/nicolas/mangafacedetector',
      forks_url: 'https://api.github.com/repos/nicolas/mangafacedetector/forks',
      keys_url: 'https://api.github.com/repos/nicolas/mangafacedetector/keys{/key_id}',
      collaborators_url:
         'https://api.github.com/repos/nicolas/mangafacedetector/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/nicolas/mangafacedetector/teams',
      hooks_url: 'https://api.github.com/repos/nicolas/mangafacedetector/hooks',
      issue_events_url:
         'https://api.github.com/repos/nicolas/mangafacedetector/issues/events{/number}',
      events_url: 'https://api.github.com/repos/nicolas/mangafacedetector/events',
      assignees_url: 'https://api.github.com/repos/nicolas/mangafacedetector/assignees{/user}',
      branches_url: 'https://api.github.com/repos/nicolas/mangafacedetector/branches{/branch}',
      tags_url: 'https://api.github.com/repos/nicolas/mangafacedetector/tags',
      blobs_url: 'https://api.github.com/repos/nicolas/mangafacedetector/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/nicolas/mangafacedetector/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/nicolas/mangafacedetector/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/nicolas/mangafacedetector/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/nicolas/mangafacedetector/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/nicolas/mangafacedetector/languages',
      stargazers_url: 'https://api.github.com/repos/nicolas/mangafacedetector/stargazers',
      contributors_url: 'https://api.github.com/repos/nicolas/mangafacedetector/contributors',
      subscribers_url: 'https://api.github.com/repos/nicolas/mangafacedetector/subscribers',
      subscription_url: 'https://api.github.com/repos/nicolas/mangafacedetector/subscription',
      commits_url: 'https://api.github.com/repos/nicolas/mangafacedetector/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/nicolas/mangafacedetector/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/nicolas/mangafacedetector/comments{/number}',
      issue_comment_url:
         'https://api.github.com/repos/nicolas/mangafacedetector/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/nicolas/mangafacedetector/contents/{+path}',
      compare_url: 'https://api.github.com/repos/nicolas/mangafacedetector/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/nicolas/mangafacedetector/merges',
      archive_url: 'https://api.github.com/repos/nicolas/mangafacedetector/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/nicolas/mangafacedetector/downloads',
      issues_url: 'https://api.github.com/repos/nicolas/mangafacedetector/issues{/number}',
      pulls_url: 'https://api.github.com/repos/nicolas/mangafacedetector/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/nicolas/mangafacedetector/milestones{/number}',
      notifications_url:
         'https://api.github.com/repos/nicolas/mangafacedetector/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/nicolas/mangafacedetector/labels{/name}',
      releases_url: 'https://api.github.com/repos/nicolas/mangafacedetector/releases{/id}',
      deployments_url: 'https://api.github.com/repos/nicolas/mangafacedetector/deployments',
      created_at: '2019-07-29T11:34:53Z',
      updated_at: '2019-07-29T12:00:54Z',
      pushed_at: '2022-06-21T22:25:05Z',
      git_url: 'git://github.com/nicolas/mangafacedetector.git',
      ssh_url: 'git@github.com:nicolas/mangafacedetector.git',
      clone_url: 'https://github.com/nicolas/mangafacedetector.git',
      svn_url: 'https://github.com/nicolas/mangafacedetector',
      homepage: null,
      size: 8,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Python',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 3,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 3,
      watchers: 0,
      default_branch: 'master',
   },
];

export const dummyData = {
   login: 'nic',
   id: 66042,
   node_id: 'MDQ6VXNlcjY2MDQy',
   avatar_url: 'https://avatars.githubusercontent.com/u/66042?v=4',
   gravatar_id: '',
   url: 'https://api.github.com/users/nic',
   html_url: 'https://github.com/nic',
   followers_url: 'https://api.github.com/users/nic/followers',
   following_url: 'https://api.github.com/users/nic/following{/other_user}',
   gists_url: 'https://api.github.com/users/nic/gists{/gist_id}',
   starred_url: 'https://api.github.com/users/nic/starred{/owner}{/repo}',
   subscriptions_url: 'https://api.github.com/users/nic/subscriptions',
   organizations_url: 'https://api.github.com/users/nic/orgs',
   repos_url: 'https://api.github.com/users/nic/repos',
   events_url: 'https://api.github.com/users/nic/events{/privacy}',
   received_events_url: 'https://api.github.com/users/nic/received_events',
   type: 'User',
   site_admin: false,
   name: 'Nic Marcondes',
   company: 'Quanto',
   blog: 'https://upNic.net',
   location: 'São Paulo, Brazil',
   email: null,
   hireable: null,
   bio: 'Chief Trolling Officer',
   twitter_username: 'upNic',
   public_repos: 45,
   public_gists: 5,
   followers: 327,
   following: 520,
   created_at: '2009-03-23T12:37:41Z',
   updated_at: '2023-01-26T17:37:23Z',
};
